### ISSUE TITLE
[FEATURE] Simplify switching between VIRTUAL and ROBOT platforms

### ISSUE THREAD

**Issue by willbotics** [UniMelbHumanRoboticsLab/CANOpenRobotController#1]
## Detailed Description
Currently there are several different MACROS in separate .h files to configure an application for use one virtual or real platform. This should either be in one place or use another mechanism to achieve the behavior. 

## Context

Needed for testing on VCAN vs. access to a real robot using can.
Currently, you change can0 to vcan0 or vice versa. With the addition of commenting #VIRUTAL_

Simplify testing and running on various platforms.
## Possible Implementation
Define in a single shared header file. 
Generalize program to use a .config file at startup to enable virtual or real macros or similar files.

**Comment by vcrocher** [comment]
If I understand you currently need to do two changes to switch:
- change char CANdevice[10] = "vcan0"; l83 in main.cpp
- define or not define #VIRUTAL_ somewhere (I can't find it)

If this is all that need to be changed, this can easily be replaced by a single DEFINE somewhere, add a pre-processor condition to define the proper can device. This define can even be set or not set in the Makefile (by adding a -D command to the compiler command), allowing to have separate directives to build for virtual or real platform.

**Comment by vcrocher** [comment]
vcan now automatically detected and more explicit NOROBOT flag.
