### ISSUE TITLE
[FEATURE] Logging Capabilities

### ISSUE THREAD

**Issue by justincmfong** [UniMelbHumanRoboticsLab/CANOpenRobotController#15]
Logging is important in any R&D platform, and thus CORC should also have them. 

## Detailed Description
There are two types of logs which need to be implemented into the toolbox:

### 1. State Log
A log at each which records the state of the system, such as joint positions/velocities/statuses, overall robot state, and possibly state machine state. The exact records should be selected either at compile or run time. 

### 2. Event Based Log
A log which records significant events, such as errors. 

## Context
This will be useful in at least two scenarios:

### 1. Research-based logging
This will likely use the State Log, and will be geared towards the particular experiment which the researcher is performing. It is also possible that this will need to synchronise with other devices (motion capture, eternal computers/screens, force plates, etc). 

### 2. Troubleshooting
Both logs will be required in this case, as information is required to identify any problems during development.  

## Possible Implementation

The state log can possibly be implemented in  `app_programControlLoop` cycle (or perhaps multiples of this if this is too resource-intensive) 

The Event-based log could potentially be implemented by defining a function that can be called from anywhere - then we would have to go through methods to try to identify where this function should be called (and also allow it to be used in new methods as well).

**Comment by vcrocher** [comment]
Sounds good.

As for implementation:
- a separate thread is probably better to 1) avoid loading the control thread, 2) allow use of non-RT functionalities for the logging (either disk writing or memory allocation for storage are not RT compatible). 
- compile time definition of values to log is probably fine and easier to implement than runtime (even just to keep the logs consistent during execution)

**Comment by emekBaris** [comment]
We might also consider using this library: https://github.com/leggedrobotics/signal_logger

Its core part is not ROS dependent. Documentation can be found here:

Overview: https://docs.leggedrobotics.com/signal_logger_doc/index.html
How to use in your program: https://docs.leggedrobotics.com/signal_logger_doc/page_use_silo.html

**Comment by vcrocher** [comment]
Logging through spdlog for both messages and states.
