### ISSUE TITLE
[BUG] Original repo for X2 model description has been removed.

### ISSUE THREAD

**Issue by zebin-huang** [UniMelbHumanRoboticsLab/CANOpenRobotController#68]
## Description

Hi, I am trying to run X2 simulation as [document](https://github.com/UniMelbHumanRoboticsLab/CANOpenRobotController/blob/master/doc/1.GettingStarted/AdvancedSimulationAndHardwareTesting.md). It seems that the original repo for model description has been removed.

## Expected Behavior

The clone should be successful

## Actual Behavior

```
Cloning into 'x2_description'...
remote: Repository not found.
fatal: repository 'https://github.com/emekBaris/x2_description.git/' not found
```

## Possible Fix
No sure.

## Steps to Reproduce

```
$ git clone https://github.com/emekBaris/x2_description.git
$ git clone https://github.com/emekBaris/cob_gazebo_plugins.git
```

## Context

We are constructing an M2 simulation and will be referencing the codes in X2.

**Comment by emekBaris** [comment]
Access is now given to "zebin-huang". Also, the address of the repo in the ReadMe is updated with [this pull request.](https://github.com/UniMelbHumanRoboticsLab/CANOpenRobotController/pull/69)

**Comment by mohamedeyaad** [comment]
Hello, 
The new address of the repo in the ReadMe file is not working, may I request you to give me access as well?
@emekBaris
