### ISSUE TITLE
x2_description package not available 

### ISSUE THREAD

**Issue by mohamedeyaad** [UniMelbHumanRoboticsLab/CANOpenRobotController#71]
Hello, 
The new address of the repo in the ReadMe file is not working, may I request you to give me access as well?
@emekBaris

_Originally posted by @mohamedeyaad in https://github.com/UniMelbHumanRoboticsLab/CANOpenRobotController/issues/68#issuecomment-2031507268_

**Comment by emekBaris** [comment]
Access now given to @mohamedeyaad. I also made @justincmfong  and @vcrocher  admin in that repo in case they need to give access to other people.
